## Deployment playbook goes here.
---
- name: Creates directory
  file:
    path: ~/backend
    state: directory

- name: Copy backend files
  template:
    src: /tmp/workspace/backend.tar.gz
    dest: ~/backend/

# command: /usr/local/bin/pm2 start npm --name backend -- start

- name: Executing node
  shell: |
    npm i tar
    ls -al
    cd ~/backend
    tar xvzf backend.tar.gz
    npm install
    npm run build 
    npm audit fix --audit-level=critical --force
    pm2 start npm --name backend -- start
