## Deployment playbook goes here.
---
- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: unarchive backend files
  become: yes
  unarchive:
    src: /tmp/workspace/backend.tar.gz
    dest: /home/ubuntu/backend/

- name: Executing node
  become: yes
  shell: |
    ls backend
    cd ~/backend/dist
    npm run build 
    npm audit fix --audit-level=critical --force
    pm2 start npm --name backend -- start
  environment:
    NODE_ENV: production
    TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_ENTITIES: "{{ lookup('env','TYPEORM_ENTITIESN') }}"
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
    TYPEORM_MIGRATIONS: "{{ lookup('env','TYPEORM_MIGRATIONS') }}"
