## Deployment playbook goes here.
---
- name: Copy backend files
  template:
    src: ~/project/backend/dist
    dest: ~/backend

# command: /usr/local/bin/pm2 start npm --name backend -- start

- name: Executing node
  shell: |
    cd ~/backend
    npm install
    npm run build 
    npm audit fix --audit-level=critical --force
    pm2 start npm --name backend -- start
