## Deployment playbook goes here.
---
- name: Creates directory
  file:
    path: ~/backend
    state: directory

- name: unarchive backend files
  become: yes
  unarchive:
    src: /tmp/workspace/backend.tar.gz
    dest: ~/backend/

- name: Executing node
  become: yes
  shell: |
    ls backend
    cd ~/backend/dist
    npm install
    npm run build 
    npm audit fix --audit-level=critical --force
    pm2 start npm --name backend -- start
